# username = ['MClaut','masnikita20','PeterGrant','Dkey112','34Alan34','kirraerr','Dinodinozavr','12345demian12345','freemclaut','lenapoleno811','AlexCoool','AndreZeltsman','saMichael','StrangeNick','nagibatar_666','andreatangus','marinakartich','jackgorobets','allabrisovna','xlamidii','faly1111','paradigm_ass','merlock111','bautits222']
# password = ['z3ebdk9z']
username = ['youngcrab']
password = ['z3ebdk9z']
keys = []
# keys = ['Hijoe6','fray','flickzy','berki','Discord500','Welcome500','welcomeGG','WEARE!','SAD','ANOMALY']
vpnl = ['faly111@gmail.com','zzezela01@gmail.com','zzezela02@gmail.com']
vpnp = ['z3ebdk9z']
